# prometheus.yml
global:
  scrape_interval: 10s

#alerting:
#  alertmanagers:
#  - static_configs:
#    - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['gateway.harmony.one']
  - job_name: 'multi-sig-backend'
    scrape_interval: 5s
    static_configs:
      - targets: ["54.153.118.255:9100", "13.57.190.45:9100"]
  - job_name: 'shard0_mainnet'
    scrape_interval: 5s
    static_configs:
      - targets: []
  - job_name: 'shard1_mainnet'
    scrape_interval: 5s
    static_configs:
      - targets: []
  - job_name: 'shard2_mainnet'
    scrape_interval: 5s
    static_configs:
      - targets: []
  - job_name: 'shard3_mainnet'
    scrape_interval: 5s
    static_configs:
      - targets: []
  - job_name: 'shard0_lrtn'
    scrape_interval: 5s
    static_configs:
      - targets: []
  - job_name: 'shard1_lrtn'
    scrape_interval: 5s
    static_configs:
      - targets: []
  - job_name: 'shard2_lrtn'
    scrape_interval: 5s
    static_configs:
      - targets: []
  - job_name: 'shard3_lrtn'
    scrape_interval: 5s
    static_configs:
      - targets: []
